# database/seed.py
# Run this once to populate the database with real gym data
from database.db import SessionLocal, engine, Base
from models.models import Gym, Trainer, FoodItem

Base.metadata.create_all(bind=engine)

def seed():
    db = SessionLocal()

    # Check if already seeded
    if db.query(Gym).count() > 0:
        print("Database already seeded!")
        db.close()
        return

    print("Seeding database with Malappuram gyms...")

    # ─── REAL GYMS IN MALAPPURAM DISTRICT ────────────────────────────────────
    gyms = [
        Gym(
            name="Your Life Gym",
            area="Wandoor",
            address="Main Road, Wandoor, Malappuram",
            city="Malappuram",
            state="Kerala",
            phone="+91 9000000001",
            latitude=11.0167,
            longitude=76.6500,
            rating=4.5,
            reviews=87,
            monthly_price=600,
            day_pass_price=80,
            open_time="5:30 AM",
            close_time="9:30 PM",
            total_capacity=40,
            current_crowd=12,
            amenities=["AC", "Trainer", "Locker", "Parking"],
            is_verified=True,
        ),
        Gym(
            name="Fitness Plus Gym",
            area="Malappuram Town",
            address="Near Bus Stand, Malappuram Town",
            city="Malappuram",
            state="Kerala",
            phone="+91 9000000002",
            latitude=11.0735,
            longitude=76.0741,
            rating=4.3,
            reviews=124,
            monthly_price=700,
            day_pass_price=100,
            open_time="6:00 AM",
            close_time="10:00 PM",
            total_capacity=60,
            current_crowd=25,
            amenities=["AC", "Trainer", "Locker", "Cardio Zone"],
            is_verified=True,
        ),
        Gym(
            name="Iron Zone Fitness",
            area="Manjeri",
            address="Court Road, Manjeri, Malappuram",
            city="Malappuram",
            state="Kerala",
            phone="+91 9000000003",
            latitude=11.1195,
            longitude=76.1193,
            rating=4.6,
            reviews=203,
            monthly_price=800,
            day_pass_price=120,
            open_time="5:00 AM",
            close_time="10:30 PM",
            total_capacity=80,
            current_crowd=45,
            amenities=["AC", "Trainer", "Locker", "Sauna", "Parking", "Cardio Zone"],
            is_verified=True,
        ),
        Gym(
            name="Power House Gym",
            area="Tirur",
            address="Station Road, Tirur, Malappuram",
            city="Malappuram",
            state="Kerala",
            phone="+91 9000000004",
            latitude=10.9140,
            longitude=75.9220,
            rating=4.2,
            reviews=98,
            monthly_price=599,
            day_pass_price=80,
            open_time="6:00 AM",
            close_time="9:00 PM",
            total_capacity=45,
            current_crowd=18,
            amenities=["Trainer", "Locker", "Cardio Zone"],
            is_verified=False,
        ),
        Gym(
            name="Gold's Fitness Center",
            area="Perinthalmanna",
            address="MG Road, Perinthalmanna, Malappuram",
            city="Malappuram",
            state="Kerala",
            phone="+91 9000000005",
            latitude=10.9769,
            longitude=76.2263,
            rating=4.7,
            reviews=312,
            monthly_price=999,
            day_pass_price=150,
            open_time="5:30 AM",
            close_time="10:00 PM",
            total_capacity=100,
            current_crowd=38,
            amenities=["AC", "Trainer", "Locker", "Sauna", "Pool", "Parking", "Cafe"],
            is_verified=True,
        ),
        Gym(
            name="Shape Up Gym",
            area="Kondotty",
            address="Near Kondotty Bus Stand, Malappuram",
            city="Malappuram",
            state="Kerala",
            phone="+91 9000000006",
            latitude=11.1870,
            longitude=75.9690,
            rating=4.1,
            reviews=56,
            monthly_price=500,
            day_pass_price=70,
            open_time="6:00 AM",
            close_time="9:30 PM",
            total_capacity=35,
            current_crowd=10,
            amenities=["Trainer", "Locker"],
            is_verified=False,
        ),
        Gym(
            name="Muscle Factory",
            area="Ponnani",
            address="Beach Road, Ponnani, Malappuram",
            city="Malappuram",
            state="Kerala",
            phone="+91 9000000007",
            latitude=10.7700,
            longitude=75.9200,
            rating=4.4,
            reviews=145,
            monthly_price=750,
            day_pass_price=100,
            open_time="5:00 AM",
            close_time="10:00 PM",
            total_capacity=55,
            current_crowd=22,
            amenities=["AC", "Trainer", "Locker", "Parking"],
            is_verified=True,
        ),
        Gym(
            name="Fit Kerala Gym",
            area="Kottakkal",
            address="Near Arya Vaidya Sala, Kottakkal",
            city="Malappuram",
            state="Kerala",
            phone="+91 9000000008",
            latitude=11.0020,
            longitude=76.0030,
            rating=4.3,
            reviews=78,
            monthly_price=650,
            day_pass_price=90,
            open_time="6:00 AM",
            close_time="9:00 PM",
            total_capacity=40,
            current_crowd=15,
            amenities=["AC", "Trainer", "Locker"],
            is_verified=True,
        ),
    ]

    db.add_all(gyms)
    db.commit()
    print(f"Added {len(gyms)} gyms!")

    # ─── TRAINERS ─────────────────────────────────────────────────────────────
    trainers = [
        Trainer(
            name="Arjun Nair",
            gym_id=1,
            specialty="Strength & Muscle Building",
            experience="5 years",
            price_per_session=500,
            rating=4.8,
            reviews=67,
            bio="Certified personal trainer specializing in muscle building and strength training. Trained 100+ clients in Malappuram.",
            certifications=["ISSA-CPT", "Nutrition Coach"],
            is_online=True,
            phone="+91 9000000010",
        ),
        Trainer(
            name="Priya Menon",
            gym_id=2,
            specialty="Weight Loss & HIIT",
            experience="4 years",
            price_per_session=400,
            rating=4.7,
            reviews=89,
            bio="Female trainer specializing in weight loss, HIIT, and diet planning. Safe space for women.",
            certifications=["ACE-CPT", "Zumba Instructor"],
            is_online=True,
            phone="+91 9000000011",
        ),
        Trainer(
            name="Rahul Krishna",
            gym_id=3,
            specialty="Powerlifting & Bodybuilding",
            experience="7 years",
            price_per_session=600,
            rating=4.9,
            reviews=134,
            bio="State-level powerlifter. Squat 160kg. Trains serious athletes and beginners alike.",
            certifications=["NSCA-CSCS", "Sports Nutrition"],
            is_online=False,
            phone="+91 9000000012",
        ),
        Trainer(
            name="Aisha Fathima",
            gym_id=5,
            specialty="Yoga & Flexibility",
            experience="6 years",
            price_per_session=350,
            rating=4.6,
            reviews=112,
            bio="RYT-500 certified yoga instructor. Specializes in stress relief, mobility and women's fitness.",
            certifications=["RYT-500", "Meditation Coach"],
            is_online=True,
            phone="+91 9000000013",
        ),
    ]

    db.add_all(trainers)
    db.commit()
    print(f"Added {len(trainers)} trainers!")

    # ─── FOOD ITEMS ───────────────────────────────────────────────────────────
    food_items = [
        FoodItem(
            name="Grilled Chicken Rice Bowl",
            restaurant="FitMeal Kerala",
            price=180,
            calories=420,
            protein=42,
            carbs=35,
            fat=10,
            category="High Protein",
            prep_time="15 min",
            tags=["High Protein", "Post-workout"],
            area="Malappuram",
        ),
        FoodItem(
            name="Egg White Omelette & Parotta",
            restaurant="Healthy Bites",
            price=120,
            calories=380,
            protein=28,
            carbs=42,
            fat=8,
            category="Breakfast",
            prep_time="10 min",
            tags=["Breakfast", "High Protein"],
            area="Malappuram",
        ),
        FoodItem(
            name="Protein Banana Shake",
            restaurant="FitMeal Kerala",
            price=99,
            calories=310,
            protein=25,
            carbs=40,
            fat=4,
            category="Shake",
            prep_time="5 min",
            tags=["Pre-workout", "Energy"],
            area="Malappuram",
        ),
        FoodItem(
            name="Fish Curry & Brown Rice",
            restaurant="Kerala Fit Kitchen",
            price=150,
            calories=460,
            protein=38,
            carbs=52,
            fat=12,
            category="Meal",
            prep_time="20 min",
            tags=["High Protein", "Kerala Special"],
            area="Malappuram",
        ),
        FoodItem(
            name="Paneer Tikka Bowl",
            restaurant="Healthy Bites",
            price=160,
            calories=380,
            protein=30,
            carbs=28,
            fat=14,
            category="Vegetarian",
            prep_time="15 min",
            tags=["Veg", "High Protein"],
            area="Malappuram",
        ),
        FoodItem(
            name="Boiled Egg & Wheat Bread",
            restaurant="Kerala Fit Kitchen",
            price=80,
            calories=280,
            protein=20,
            carbs=30,
            fat=8,
            category="Breakfast",
            prep_time="8 min",
            tags=["Breakfast", "Budget Friendly"],
            area="Wandoor",
        ),
    ]

    db.add_all(food_items)
    db.commit()
    print(f"Added {len(food_items)} food items!")

    print("✅ Database seeded successfully!")
    db.close()

if __name__ == "__main__":
    seed()
